config setup
    charondebug="ike 2, knl 2, cfg 2"
    uniqueids=no

conn ikev2-eap
    keyexchange=ikev2
    ike=aes256-sha256-modp2048,aes128-sha256-modp2048,aes256-sha1-modp2048,aes256-sha256-ecp256!
    esp=aes256-sha256,aes128-sha256,aes256-sha1!
    left=%any
    leftid=YOUR_PUBLIC_IP
    leftcert=server.crt
    leftsendcert=always
    leftsubnet=192.168.1.0/24
    #leftsubnet=0.0.0.0/0
    right=%any
    rightid=%any
    rightauth=eap-mschapv2
    rightsourceip=10.10.10.0/24
    rightdns=223.5.5.5,114.114.114.114
    eap_identity=%identity
    auto=add
